<?xml version="1.0"?>

<!-- XML namespaces -->
  <robot name="gizmo" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="PI" value="3.1415" />  
    <xacro:property name="M_PI" value="3.14159"/>
    <xacro:property name="M_SCALE" value="0.001"/>
    <xacro:property name="C_SCALE" value="0.0034"/>
    <xacro:property name="MESH_EXT" value="stl"/>
    <xacro:property name="color" value="grey1"/>

 <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="d435_cam_depth_to_infra1_offset" value="0.0"/>
    <xacro:property name="d435_cam_depth_to_infra2_offset" value="-0.050"/>
    <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>

    <!-- The following values model the aluminum peripherial case for the
  	D435 camera, with the camera joint represented by the actual
  	peripherial camera tripod mount -->
    <xacro:property name="d435_cam_width" value="0.090"/>
    <xacro:property name="d435_cam_height" value="0.025"/>
    <xacro:property name="d435_cam_depth" value="0.02505"/>
    <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>

    <!-- The following offset is relative the the physical D435 camera peripherial
  	camera tripod mount -->
    <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
    <xacro:property name="d435_cam_depth_py" value="0.0175"/>
    <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>
    <xacro:include filename="$(find robbie)/urdf/hardware.xacro" />
    <xacro:include filename="$(find robbie)/urdf/mantis_gripper.xacro" />
   



<xacro:my_box name="base_footprint" lwh="0.1 0.1 0.005" xyz="0 0 0" rpy="0 0 0" mass="0.1" material="Gazebo/FlatBlack">
	        <xacro:gold />
        </xacro:my_box>

<xacro:my_box name="imu_base" lwh="0.01 0.01 0.005" xyz="0 0 0" rpy="0 0 0" mass="0.1" material="Gazebo/FlatBlack">
	        <xacro:black />
        </xacro:my_box>

<link name="base_link" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/base.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/base.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>


  <link name="kinect_link">
      <inertial>
        <mass value="1.0" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                 iyy="1.0" iyz="0.0"
                 izz="1.0" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/kinect.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
        </geometry>
        <xacro:ax12_color />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/kinect.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>

    </link>

   <xacro:my_box name="elbow_joint_r" lwh="0.042 0.042 0.042" xyz="0 0 0" rpy="0 0 0" mass="0.1" material="Gazebo/FlatBlack">
	        <xacro:yellow2 />
        </xacro:my_box>

<xacro:my_box name="elbow_joint_l" lwh="0.042 0.042 0.042" xyz="0 0 0" rpy="0 0 0" mass="0.1" material="Gazebo/FlatBlack">
	        <xacro:yellow2 />
        </xacro:my_box>


<link name="torso_link" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/gizmo2_torso.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:grey1/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
        <origin xyz="-0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/gizmo2_torso.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="scanner_link" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/X4.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:grey1/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
        <origin xyz="-0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/X4.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<xacro:ax12 name="pan_link" xyz="0 0 0" rpy=" 1.57 0 1.57">
	</xacro:ax12>

<xacro:my_box name="head_pan_link" lwh="0.15 0.1 0.005" xyz="0 0 0" rpy="0 0 0" mass="0.1" material="Gazebo/FlatBlack">
	        <xacro:blue />
        </xacro:my_box>

<xacro:ax12 name="head_tilt_link" xyz="0 0 0" rpy="0 0 3.14">
	</xacro:ax12>

<xacro:F2_bracket name="head_tilt_r_bracket_f2" xyz="0 0 0" rpy="0 0 0" />

<link name="neck" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/gizmo_neck1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:grey1/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
        <origin xyz="-0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/gizmo_neck1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="head" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/head1.stl" scale="${C_SCALE} ${C_SCALE} ${C_SCALE}"/>
      </geometry>
         <xacro:grey1/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
        <origin xyz="-0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/head1.stl" scale="${C_SCALE} ${C_SCALE} ${C_SCALE}"/>
          </geometry>
      </collision>
  </link>
<xacro:my_cylinder name="camera_link" l="0.025" r="0.01" xyz="0 0 0" rpy="0 1.57 0" mass="0.1" material="Gazebo/Grey">		
      <xacro:grey1 />
	</xacro:my_cylinder>

<link name="right_rotate" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/gizmo2_servo_r.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:black/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
        <origin xyz="-0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/gizmo2_servo_r.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="left_rotate" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/gizmo2_servo_l.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:black/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
        <origin xyz="-0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/gizmo2_servo_l.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>


<link name="right_lift_link" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/gizmo_upper_arm_r2.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:grey1/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
        <origin xyz="-0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/gizmo_upper_arm_r2.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="left_lift_link" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/gizmo_upper_arm_l2.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:grey1/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
        <origin xyz="-0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/gizmo_upper_arm_l2.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="servo_r4" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="r_bracket5" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="servo_r5" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="r_bracket6" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="servo_r6" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="r_bracket7" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="servo_r7" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="r_bracket8" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="servo_l4" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="l_bracket5" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="servo_l5" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="l_bracket6" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="servo_l6" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="l_bracket7" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="servo_l7" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/servo.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<link name="l_bracket8" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/drive_bracket1.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

<!--############################# right arm ################-->

<joint name="joint8" type="revolute">
    	<parent link="torso_link" />
    	<child link="right_rotate" />
        <origin xyz="0.01 -0.13 0.65" rpy="0 0 0" />
    	<axis xyz="0 0 1" />
    	<limit lower="-0.89" upper="1.41" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="joint9" type="revolute">
    	<parent link="right_rotate" />
    	<child link="right_lift_link" />
        <origin xyz="0 -0.03 -0" rpy="0 0 0" />
    	<axis xyz="0 1 0" />
    	<limit lower="-2" upper="2" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="joint10" type="revolute">
    	<parent link="right_lift_link" />
    	<child link="elbow_joint_r" />
        <origin xyz="0.15 -0.03 -0" rpy="0 0 0" />
    	<axis xyz="1 0 0" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="servo_r4_link" type="fixed">
    	<parent link="elbow_joint_r" />
    	<child link="servo_r4" />
        <origin xyz="0.02 -0.02 -0.01" rpy="1.57 0 1.57" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="joint11" type="revolute">
    	<parent link="servo_r4" />
    	<child link="r_bracket5" />
        <origin xyz="0.02 0.01 0.04" rpy="0 3.14 1.57" />
    	<axis xyz="0 1 0" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="servo_r5_link" type="fixed">
    	<parent link="r_bracket5" />
    	<child link="servo_r5" />
        <origin xyz="0.02 -0.01 -0.02" rpy="0 3.14 0" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="joint12" type="revolute">
    	<parent link="servo_r5" />
    	<child link="r_bracket6" />
        <origin xyz="0.02 0.01 0.04" rpy="0 3.14 1.57" />
    	<axis xyz="0 1 0" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="joint13" type="revolute">
    	<parent link="r_bracket6" />
    	<child link="servo_r6" />
        <origin xyz="0.02 0 -0.02" rpy="0 3.14 0" />
        <axis xyz="0 0 1" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="servo_r6_link" type="fixed">
    	<parent link="servo_r6" />
    	<child link="r_bracket7" />
        <origin xyz="0.02 0.01 0.04" rpy="0 3.14 1.57" />
    	<axis xyz="0 1 0" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="servo_r7_link" type="fixed">
    	<parent link="servo_r6" />
    	<child link="servo_r7" />
        <origin xyz="0 0 0.06" rpy="0 0 0" />
    	<axis xyz="0 1 0" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="joint14" type="revolute">
    	<parent link="servo_r7" />
    	<child link="r_bracket8" />
        <origin xyz="0.02 0 0.04" rpy="0 3.14 1.57" />
        <axis xyz="0 1 0" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<!-- Attach the right gripper -->
   <gripper side="right" num="joint15" reflect="1" parent="r_bracket8">
     <origin xyz="0.0 0 0" rpy="0 0 0" /> 
   </gripper>


 

<!-- ##############################   joints ##################333333--> 

<joint name="base_footprint" type="fixed">
    	<parent link="base_footprint" />
    	<child link="base_link" />
    	<origin xyz="0.06 0 0.06" rpy="0 0 0" />
	</joint> 

<joint name="torso_link" type="fixed">
    	<parent link="base_link" />
    	<child link="torso_link" />
    	<origin xyz="0.0 0 0.012" rpy="0 0 0" />
	</joint>

<joint name="imu_link" type="fixed">
    	<parent link="base_link" />
    	<child link="imu_base" />
    	<origin xyz="0.0 0 0.72" rpy="0 0 0" />
	</joint>


<joint name="laser_frame" type="fixed">
    	<parent link="base_link" />
    	<child link="scanner_link" />
    	<origin xyz="0.1 0 0.63" rpy="0 0 3.14" />
	</joint>



<joint name="pan_link" type="fixed">
    	<parent link="torso_link" />
    	<child link="pan_link" />
    	<origin xyz="0.02 0 0.68" rpy="0 0 0" />
	</joint> 


<!-- head_pan_joint-->	
	<joint name="joint16" type="revolute">
    	<parent link="pan_link" />
    	<child link="head_pan_link" />
    	<origin xyz="-0.04 0 0.02" rpy="0 0 3.14159" />
        <origin xyz="0 0 0.0" rpy="0 0 0" />
    	<axis xyz="0 0 1" />
    	<limit lower="-2" upper="2" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<!-- head_tilt_servo-->	
	<joint name="head_tilt_link" type="fixed">
    	<parent link="head_pan_link" />
    	<child link="head_tilt_link" />
    	<origin xyz="-0.06 0 0.04" rpy="0 0 0" />
      
	</joint>

<!-- head_tilt_joint-->	
	<joint name="joint17" type="revolute">
    	<parent link="head_tilt_link" />
    	<child link="head_tilt_r_bracket_f2" />
        <origin xyz="0 0 0.0" rpy="0 0 3.14" />
    	<axis xyz="0 1 0" />
    	<limit lower="2" upper="-2" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<!-- neck-->	
	<joint name="neck_link" type="fixed">
    	<parent link="head_tilt_r_bracket_f2" />
    	<child link="neck" />
    	<origin xyz="0 0 0.05" rpy="0 0 0" />   
	</joint>

<!-- head-->	
	<joint name="head_link" type="fixed">
    	<parent link="neck" />
    	<child link="head" />
    	<origin xyz="0 0 0.05" rpy="0 0 0" />   
	</joint>

<!-- camera-->	
	<joint name="camera_link" type="fixed">
    	<parent link="head" />
    	<child link="camera_link" />
    	<origin xyz="0.065 0.055 0.005" rpy="0 0 3.14159" />   
	</joint>

<link name="d435_link">
      <visual>
        <origin xyz="${d435_cam_mount_from_center_offset} ${-d435_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <!--<box size="${d435_cam_width} ${d435_cam_height} ${d435_cam_depth}"/> -->
	        <mesh filename="package://robbie/mesh/d435.dae" /> 
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 ${-d435_cam_depth_py} 0" rpy="0 0 0"/>
        <geometry>
          <box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>




   

<!--############################# left arm ################-->

<joint name="joint0" type="revolute">
    	<parent link="torso_link" />
    	<child link="left_rotate" />
        <origin xyz="0.01 0.13 0.65" rpy="0 0 0" />
    	<axis xyz="0 0 1" />
    	<limit lower="-1.34" upper="1.15" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="joint1" type="revolute">
    	<parent link="left_rotate" />
    	<child link="left_lift_link" />
        <origin xyz="0 0.03 0" rpy="0 0 0" />
    	<axis xyz="0 1 0" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>


<joint name="joint2" type="revolute">
    	<parent link="left_lift_link" />
    	<child link="elbow_joint_l" />
        <origin xyz="0.15 0.03 -0" rpy="0 0 0" />
    	<axis xyz="1 0 0" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="servo_l4_link" type="fixed">
    	<parent link="elbow_joint_l" />
    	<child link="servo_l4" />
        <origin xyz="0.02 -0.02 -0.01" rpy="1.57 0 1.57" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="joint3" type="revolute">
    	<parent link="servo_l4" />
    	<child link="l_bracket5" />
        <origin xyz="0.02 0.01 0.04" rpy="0 3.14 1.57" />
    	<axis xyz="0 1 0" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="servo_l5_link" type="fixed">
    	<parent link="l_bracket5" />
    	<child link="servo_l5" />
        <origin xyz="0.02 -0.01 -0.02" rpy="0 3.14 0" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="joint4" type="revolute">
    	<parent link="servo_l5" />
    	<child link="l_bracket6" />
        <origin xyz="0.02 0.01 0.04" rpy="0 3.14 1.57" />
    	<axis xyz="0 1 0" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="joint5" type="revolute">
    	<parent link="l_bracket6" />
    	<child link="servo_l6" />
        <origin xyz="0.02 0 -0.02" rpy="0 3.14 0" />
        <axis xyz="0 0 1" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="servo_l6_link" type="fixed">
    	<parent link="servo_l6" />
    	<child link="l_bracket7" />
        <origin xyz="0.02 0.01 0.04" rpy="0 3.14 1.57" />
    	<axis xyz="0 1 0" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="servo_l7_link" type="fixed">
    	<parent link="servo_l6" />
    	<child link="servo_l7" />
        <origin xyz="0 0 0.06" rpy="0 0 0" />
    	<axis xyz="0 1 0" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<joint name="joint6" type="revolute">
    	<parent link="servo_l7" />
    	<child link="l_bracket8" />
        <origin xyz="0.02 0 0.04" rpy="0 3.14 1.57" />
        <axis xyz="0 1 0" />
    	<limit lower="-1.57" upper="1.57" effort="100" velocity="0.5" />
      	<dynamics damping="0.0"/>
	</joint>

<!-- Attach the left gripper -->
   <gripper side="left" num="joint7" reflect="-1" parent="l_bracket8">
     <origin xyz="0.0 0 0" rpy="0 0 0" /> 
   </gripper>



  <joint name="kinect_joint" type="fixed">
    	<parent link="base_link" />
    	<child link="kinect_link" />
    	<origin xyz="0.09 0 0.22" rpy="0 0 0" />
	</joint>
<joint name="kinect_depth_joint" type="fixed">
         <origin xyz="0 0.0125 0.015" rpy="0 0 0" />
          <parent link="kinect_link" />
          <child link="kinect_depth_frame" />
      </joint>

      <link name="kinect_depth_frame">
      <inertial>
         <mass value="0.000001" />
         <origin xyz="0 0 0" />
         <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
            iyy="0.0001" iyz="0.0"
            izz="0.0001" />
         </inertial>
      </link>

      <joint name="kinect_depth_optical_joint" type="fixed">
         <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}" />
         <parent link="kinect_depth_frame" />
         <child link="kinect_depth_optical_frame" />
      </joint>

      <link name="kinect_depth_optical_frame">
         <inertial>
            <mass value="0.000001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001" />
         </inertial>
      </link>

      <joint name="kinect_rgb_joint" type="fixed">
         <origin xyz="0 -0.0125 0.01" rpy="0 0 0" />
         <parent link="kinect_link" />
         <child link="kinect_rgb_frame" />
      </joint>

      <link name="kinect_rgb_frame">
         <inertial>
         <mass value="0.000001" />
         <origin xyz="0 0 0" />
         <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
            iyy="0.0001" iyz="0.0"
            izz="0.0001" />
         </inertial>
      </link>

      <joint name="kinect_rgb_optical_joint" type="fixed">
         <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}" />
         <parent link="kinect_rgb_frame" />
         <child link="kinect_rgb_optical_frame" />
      </joint>

      <link name="kinect_rgb_optical_frame">
         <inertial>
            <mass value="0.000001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001" />
         </inertial>
      </link>

   <joint name="d435_joint" type="fixed">
    	<parent link="head" />
    	<child link="d435_link" />
    	<origin xyz="0.02 0.018 -0.06" rpy="0 0 0" />
	</joint>


</robot>
