<?xml version="1.0"?>

<!-- XML namespaces -->
  <robot name="robbie" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="PI" value="3.1415" />  
    <xacro:property name="M_PI" value="3.14159"/>
    <xacro:property name="M_SCALE" value="0.001"/>
    <xacro:property name="C_SCALE" value="0.0034"/>
    <xacro:property name="MESH_EXT" value="stl"/>
    <xacro:property name="color" value="grey1"/>

 <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="d435_cam_depth_to_infra1_offset" value="0.0"/>
    <xacro:property name="d435_cam_depth_to_infra2_offset" value="-0.050"/>
    <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>
    

    <!-- The following values model the aluminum peripherial case for the
  	D435 camera, with the camera joint represented by the actual
  	peripherial camera tripod mount -->
    <xacro:property name="d435_cam_width" value="0.090"/>
    <xacro:property name="d435_cam_height" value="0.025"/>
    <xacro:property name="d435_cam_depth" value="0.02505"/>
    <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>

    <!-- The following offset is relative the the physical D435 camera peripherial
  	camera tripod mount -->
    <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
    <xacro:property name="d435_cam_depth_py" value="0.0175"/>
    <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>
    <xacro:include filename="$(find robbie)/urdf/hardware.xacro" />
    
   



<xacro:my_box name="base_footprint" lwh="0.1 0.1 0.005" xyz="0 0 0" rpy="0 0 0" mass="0.1" material="Gazebo/FlatBlack">
	        <xacro:gold />
        </xacro:my_box>

<xacro:my_box name="imu_base" lwh="0.01 0.01 0.005" xyz="0 0 0" rpy="0 0 0" mass="0.1" material="Gazebo/FlatBlack">
	        <xacro:black />
        </xacro:my_box>

<link name="base_link" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/base2.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/base2.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>

  <link name="camera_link">
      <visual>
        <origin xyz="${d435_cam_mount_from_center_offset} ${-d435_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <!--<box size="${d435_cam_width} ${d435_cam_height} ${d435_cam_depth}"/> -->
	        <mesh filename="package://robbie/mesh/d435.dae" /> 
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 ${-d435_cam_depth_py} 0" rpy="0 0 0"/>
        <geometry>
          <box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>
    
    <link name="scanner_link" >
   <visual>
      <geometry>
        <mesh filename="package://robbie/mesh/rplidar.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
      </geometry>
         <xacro:White/>
      <origin rpy="1.57 0 0" xyz="0 0 0"/>
    </visual>
   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robbie/mesh/rplidar.stl" scale="${M_SCALE} ${M_SCALE} ${M_SCALE}"/>
          </geometry>
      </collision>
  </link>


   
 

<!-- ##############################   joints ##################333333--> 

<joint name="base_footprint" type="fixed">
    	<parent link="base_footprint" />
    	<child link="base_link" />
    	<origin xyz="0.06 0 0.2" rpy="0 0 0" />
	</joint> 


<joint name="imu_link" type="fixed">
    	<parent link="base_link" />
    	<child link="imu_base" />
    	<origin xyz="0.0 0 0.1" rpy="0 0 0" />
	</joint>
	
<joint name="scanner_link" type="fixed">
    	<parent link="base_link" />
    	<child link="scanner_link" />
    	<origin xyz="-0.038 0.038 0.15" rpy="0 0 0" />
	</joint>


<!-- camera-->	
   <joint name="camera_link" type="fixed">
    	<parent link="base_link" />
    	<child link="camera_link" />
    	<origin xyz="0.1 0 0.30" rpy="0 0 0" />
	</joint>
	
  <!-- camera depth joints and links -->
      <joint name="camera_depth_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="camera_link"/>
        <child link="camera_depth_frame" />
      </joint>
      <link name="camera_depth_frame"/>


</robot>
